### ISSUE TITLE
Cannot initialize DotEnv

### ISSUE THREAD

**Issue by sujaykakkad** [SwiftOnTheServer/SwiftDotEnv#1]
```
import DotEnv

let env = DotEnv(withFile: ".env")

```

It throws runtime error

```
fatal error: Index out of range
```

**Comment by jodihum** [comment]
@sujaykakkad you might have a line in your .env file that looks empty but isn't (has spaces etc)

**Comment by akrabat** [comment]
Please test with version `1.0.1`. If there's still a problem, please post your `.env` file.

**Comment by sujaykakkad** [comment]
It is working. I just removed extra spaces and newlines and now it is getting the env file.
Is there a way where I can give the absolute path of the .env file?
