### ISSUE TITLE
Tag needs to be in x.x.x format for SPM

### ISSUE THREAD

**Issue by mdiasdev** [SwiftOnTheServer/SwiftDotEnv#11]
Swift Package Manager accepts the x.x format for the tag. However, it indefinitely hangs while trying to download and build the project.

**Comment by mdiasdev** [comment]
**Correction**: SPM doesn't allow x.x, but allows you to make it x.x.x (whether or not that matches the tag) and it is that that hangs indefinitely

**Comment by jonnymacs** [comment]
+1 please update the tag to be 2.0.0

**Comment by akrabat** [comment]
I've created tag `2.0.0` and removed `2.0`
