### ISSUE TITLE
Must deal with relocation of packages with Swift 3.1 SwiftPM

### ISSUE THREAD

**Issue by jaredkhan** [SwiftOnTheServer/SwiftDotEnv#3]
Swift 3.1 introduced changes to the Swift package manager that mean the package is no longer necessarily located in the Packages directory, will require a rethink of the `getAbsolutePath` function.

More info in the implemented swift-evolution proposal: https://github.com/apple/swift-evolution/blob/master/proposals/0082-swiftpm-package-edit.md#detailed-design

**Comment by akrabat** [comment]
Thanks!

**Comment by akrabat** [comment]
Fixed (at least for a non-edited package) with version 1.0.2
