### ISSUE TITLE
It seems getAbsolutePath() get the wrong path.

### ISSUE THREAD

**Issue by NeoChow** [SwiftOnTheServer/SwiftDotEnv#4]
I think the line 113 in DotEnv.swift should be `let toRootDir = components[0..<components.count - 6]`

**Comment by NeoChow** [comment]
I've just made a fix. : )
https://github.com/SwiftOnTheServer/SwiftDotEnv/pull/6

**Comment by akrabat** [comment]
Fixed (at least for a non-edited package) with version 1.0.2
