### ISSUE TITLE
Not able to locate the path of .env

### ISSUE THREAD

**Issue by portergoh** [SwiftOnTheServer/SwiftDotEnv#7]
Hi 

I have placed .env in the root of my project. But it is not able to detect it.

I am running Mac OS.  When i checkout the source code and do some debugging, i realized the filepath for this statement

 var filePath = "/" + toRootDir.joined(separator: "/") + relativePath
    
is actually printing /users/.env -- Where should we place the .env ?

I realized there is this function

 public func loadDotEnvFile(filename: String) {

        let path = getAbsolutePath(relativePath: "/\(filename)", useFallback: false)
...
}

useFallback by default is set to false -- not sure why ?  IF i set it to True and recompile the code, it is able to detect correctly in my Project root directory.

**Comment by akrabat** [comment]
Which version of Swift are you using?

**Comment by portergoh** [comment]
Hi 

I am using the latest swift 3.1

**Comment by dtweston** [comment]
I'm encountering the same issue.

If I build the app in release mode, the DotEnv.swift file is located in `$ROOT/.build/checkouts/SwiftDotEnv.git--[number]/Sources/DotEnv`
If I edit the package, the source file is located in
`$ROOT/Packages/SwiftDotEnv/Sources/DotEnv`

In those two different modes, the file is located at different levels, so the current code in `getAbsolutePath` can never work for both. Would it be possible to just treat the filename as relative to the current path? That seems like it would be the most straight-forward.

**Comment by akrabat** [comment]
Yeah. Would love a PR if you have time.

**Comment by akrabat** [comment]
Try version `1.1.0` - the path to the `.env` file is now relative to the binary.
